# Use an official Python image
FROM python:3.9-slim

# Install PostgreSQL client and dependencies
RUN apt-get update && apt-get install -y postgresql-client gcc python3-dev libpq-dev

# Set the working directory
WORKDIR /app

# Copy all the project files to the container
COPY . .

# Install required Python dependencies
RUN pip install psycopg2-binary faker

# Wait for the database to start, then run the seed script
CMD ["bash", "-c", "sleep 10 && PGPASSWORD=password psql -h postgres -U test_user -d task_manager_db -f create_tables.sql && python seed.py &&  python test_database.py"]
